function plotcv3(M,C,varargin)
    [~,nM] = size(M);
    [~,nC] = size(C);
    
    hold on
    if nC > 1
        for idx = 1:nM
            plot3(  [C(1,idx),M(1,idx)], ...
                    [C(2,idx),M(2,idx)], ...
                    [C(3,idx),M(3,idx)], ...
                    varargin{:}        ...
                   );
        end
    else
        for idx = 1:nM
            plot3(  [C(1,1),M(1,idx)], ...
                    [C(2,1),M(2,idx)], ...
                    [C(3,1),M(3,idx)], ...
                    varargin{:}        ...
                   );
        end
    end
end